### ISSUE TITLE
Cannot find module .../pty-v0.1.2-node-v59-linux-x64/pty.node

### ISSUE THREAD

**Issue by tim-soft** [facebook-atom/nuclide-prebuilt-libs#9]
Running a remote terminal via Nuclide results in this error:
- Atom 1.24.0
- Nuclide 0.286.0
- Node 9.6.1 
```
Error: Cannot find module '/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.2-node-v59-linux-x64/pty.node'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/lib/unixTerminal.js:17:11)
    at Module._compile (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/lib/index.js:9:16)
    at Module._compile (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _load_pty (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/pkg/nuclide-pty-rpc/lib/PtyService.js:170:41)
    at new PtyImplementation (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/pkg/nuclide-pty-rpc/lib/PtyService.js:236:38)
    at RpcConnection.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/pkg/nuclide-pty-rpc/lib/PtyService.js:23:12)
    at Generator.next (<anonymous>)
    at step (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:24:9)
    at <anonymous>
```

Jumping into `node_modules/nuclide-prebuilt-libs/pty/build` It seems like these other builds of pty were made just fine
```
pty-v0.0.2-node-v57-darwin-x64       pty-v0.1.2-electron-v1.6-win32-x64   pty-v0.1.2-node-v51-darwin-x64
pty-v0.1.0-node-v57-darwin-x64       pty-v0.1.2-electron-v1.7-darwin-x64  pty-v0.1.2-node-v51-linux-x64
pty-v0.1.2-electron-v1.6-darwin-x64  pty-v0.1.2-electron-v1.7-linux-x64   pty-v0.1.2-node-v51-win32-x64
pty-v0.1.2-electron-v1.6-linux-x64   pty-v0.1.2-electron-v1.7-win32-x64
```

Have any ideas where `pty-v0.1.2-node-v59-linux-x64/pty.node` went to? Maybe these packages are only supported on older node versions?

Checking my nuclide logs, it also appears that `nuclide-prebuilt-libs/fuzzy-native/build/fuzzy-native-v0.6.6-node-v59-linux-x64/fuzzy-native.node` is also missing, although expected by the system.

```
[2018-02-28 23:55:21.307] [ERROR] nuclide-fuzzy-native - Failed to load native fuzzy matching. Falling back to JS implementation { Error: Cannot find module '/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/build/fuzzy-native-v0.6.6-node-v59-linux-x64/fuzzy-native.node'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/lib/main.js:6:18)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by hansonw** [comment]
Yes, for this package we've only prebuilt binaries for Node versions corresponding to Electron versions corresponding to Atom versions (Phew!) Currently Atom 1.23/1.24 correspond to Node 7.4.0, and Atom 1.25 corresponds to Node 7.9.0, both of which are covered by this package.

It's not well documented, but it's recommended that you start the Nuclide server with one of these Node versions - I see that you're already using NVM, so using 7.4.0 or 7.9.0 should both work. Sorry about that!
